# Generated by Django 5.1.4 on 2025-01-11 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doors', models.PositiveIntegerField()),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('convertible', 'Kabriolet'), ('wagon', 'Kombi'), ('van', 'Van')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manualna'), ('automatic', 'Automatyczna')], max_length=10)),
                ('seats', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzyna'), ('diesel', 'Diesel'), ('electric', 'Elektryczny'), ('hybrid', 'Hybrydowy')], max_length=10)),
                ('trunk_size', models.PositiveIntegerField(help_text='Pojemność bagażnika w litrach')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Poczatek rezerwacji')),
                ('end_date', models.DateField(verbose_name='Koniec rezerwacji')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
