# Generated by Django 5.1.4 on 2025-01-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(choices=[(2, '2 doors'), (3, '3 doors'), (4, '4 doors'), (5, '5 doors')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='trunk_size',
            field=models.PositiveIntegerField(help_text='Trunk capacity in liters'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(verbose_name='End of reservationi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(verbose_name='Start of reservation'),
        ),
    ]
