# Generated by Django 5.1.4 on 2025-01-12 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_car_type_alter_car_doors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("hatchback", "Hatchback"),
                    ("suv", "SUV"),
                    ("coupe", "Coupe"),
                    ("convertible", "Kabriolet"),
                    ("wagon", "Kombi"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.PositiveIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "Benzyna"),
                    ("diesel", "Diesel"),
                    ("electric", "Elektryczny"),
                    ("hybrid", "Hybrydowy"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seats",
            field=models.PositiveIntegerField(
                choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("manual", "Manualna"), ("automatic", "Automatyczna")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="trunk_size",
            field=models.PositiveIntegerField(
                help_text="Pojemność bagażnika w litrach"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1999),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(verbose_name="End of reservation"),
        ),
    ]
