# Generated by Django 5.1.4 on 2025-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_car_type_alter_car_doors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_photos/"),
        ),
    ]
