# Generated by Django 5.1.4 on 2025-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
