# Generated by Django 5.1.4 on 2025-01-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="is_available",
        ),
    ]
